name: 'Deploy GitHub Pages site'
description: 'A GitHub Action to deploy an artifact as a GitHub Pages site'
author: 'GitHub'
runs:
  using: 'node24'
  main: 'dist/index.js'
inputs:
  token:
    description: 'GitHub token'
    default: ${{ github.token }}
    required: true
  path:
    description: 'Path of the directory containing the static assets.'
    required: true
    default: "dist/"
  expire:
    description: 'Duration after which artifact will be deleted in seconds.'
    required: true
    default: 0.5

outputs:
  page_url:
    description: 'URL to deployed GitHub Pages'