name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1  # needed for gh-pages deployment

      - name: Create Html
        run: |
          mkdir dist
          cd dist
          echo "<html><head><script src="index.js"></script></head><body><h1>Hello, world. final</h1><p>This is a test page</p></body></html>" > index.html
          echo "window.onload = () => { const p = document.createElement('p'); p.append('JS is running'); document.body.appendChild(p); }" > index.js
          cd ..

      - name: Deploy to GitHub Pages
        id: deployment
        uses: Yi-Jun-Wu/deploy-test/.github/actions/deploy@main
          
